### ISSUE TITLE
werkzeug.BaseRequest Deprecated

### ISSUE THREAD

**Issue by erdem** [sivel/flask-lambda#13]
I have discovered werkzeug removed `BaseRequest` class later 2.1.0 version. 

[Related discussion here.](https://github.com/pallets/werkzeug/issues/2360#issuecomment-1081009270)

The package works fine with `2.0.3` version as well as tested. However, would be great if you can specify the exact dependent werkzeug version or fix the deprecated implementation.

Thanks

**Comment by joranbeasley** [comment]
```
from werkzeug.wrappers import BaseRequest
>>> from werkzeug.wrappers import BaseRequest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'BaseRequest' from 'werkzeug.wrappers' (E:\flask-webhook-creator\venv\lib\site-packages\werkzeug\wrappers\__init__.py) 

```

**Comment by joranbeasley** [comment]
see: https://github.com/sivel/flask-lambda/pull/14  for potential fix

**Comment by yalattas** [comment]
I've installed the package and tried to run the app and its throw same error

```
{"errorMessage": "Unable to import module 'run': cannot import name 'BaseRequest' from 'werkzeug.wrappers' (/var/task/werkzeug/wrappers/__init__.py)", "errorType": "Runtime.ImportModuleError"
```

Thanks to @erdem, I fixed it by downgrading the package to `Werkzeug==2.0.3` in `requirements.txt`

**Comment by iitow** [comment]
Question is a 0.0.5 pkg going to be released?
